AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: ntier flask server AWS Lambda function.

Resources:
  
  FlaskServerServerless:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.py
      Runtime: python
      Description: ntier flask server AWS Lambda function.
      MemorySize: 128
      Timeout: 3
